development:
  adapter: postgresql
  encoding: unicode
  database: mytrain_development
  pool: 5

test: &test
  adapter: postgresql
  encoding: unicode
  database: mytrain_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: mytrain_production
  pool: 5

cucumber:
  <<: *test